spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/railway_repository
    username: postgres
    password: postgres
#    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
#
#server:
#  error:
#    include-binding-errors: always
#    include-message: always